services:
  app-frontend:
    build:
      context: ./FRONT/gerenciador
    container_name: react-app
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - app-backend
    networks:
      - network-application

  app-backend:
    build:
      context: ./BACK/main
    container_name: spring-boot-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_PROFILES_ACTIVE=homolog
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    depends_on:
      - db
    env_file:
      - ./BACK/main/.env
    networks:
      - network-application

  db:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=PedidosDB
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - network-application

networks:
  network-application:
    driver: bridge

volumes:
  db_data:
