services:
  app-frontend:
    build:
      context: ./FRONT/gerenciador
      args:
        VITE_API_URL: http://localhost:8080
    container_name: react-app
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - app-backend
    networks:
      - network-application

  app-backend:
    build:
      context: ./BACK/main
    container_name: spring-boot-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: my-secret-key
      SPRING_PROFILES_ACTIVE: homolog
    depends_on:
      - db
    networks:
      - network-application

  db:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: PedidosDB
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - network-application

networks:
  network-application:
    driver: bridge

volumes:
  db_data:
